### ISSUE TITLE
CardCollection fails on dismiss: '!_disqualifiedFromEverAppearingAgain' is not true.

### ISSUE THREAD

**Issue by HansMuller** [domokit/sky_engine#1068]
The card_collection.dart example just stopped working. Dragging a card causes this assert:

```
E/chromium(22444): [ERROR:dart_error.cc(16)] Unhandled exception:
E/chromium(22444): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 896 pos 12: '!_disqualifiedFromEverAppearingAgain' is not true.
E/chromium(22444): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium(22444): #1      StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:896:12)
E/chromium(22444): #2      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:457:13)
E/chromium(22444): #3      OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1327:14)
E/chromium(22444): #4      Opacity.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:52:27)
E/chromium(22444): #5      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1085:5)
E/chromium(22444): #6      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:457:13)
E/chromium(22444): #7      StatefulComponent.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:920:27)
E/chromium(22444): #8      Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:818:14)
E/chromium(22444): #9      StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:904:16)
E/chromium(22444): #10     Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:841:5)
E/chromium(22444): #11     StatefulComponent._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:875:24)
E/chromium(22444): #12     _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:981:19)
E/chromium(22444): #13     Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:854:7)
E/chromium(22444): #14     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1450:15)
E/chromium(22444): #15     beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:45:13)
```

**Comment by HansMuller** [comment]
This problem also occurs if you run the stocks demo and try and open the drawer.

**Comment by HansMuller** [comment]
This still fails although the symptoms have changed. Now dragging a card causes this assert:

```
E/chromium(10085): [ERROR:dart_error.cc(16)] Unhandled exception:
E/chromium(10085): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 1359 pos 12: 'renderObject.child == child.renderObject' is not true.
E/chromium(10085): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium(10085): #1      OneChildRenderObjectWrapper.detachChildRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1359:12)
E/chromium(10085): #2      RenderObjectWrapper.detachRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1294:15)
E/chromium(10085): #3      Component.detachRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:773:14)
E/chromium(10085): #4      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:443:20)
E/chromium(10085): #5      OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1343:14)
E/chromium(10085): #6      Opacity.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:53:27)
E/chromium(10085): #7      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1095:5)
E/chromium(10085): #8      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:465:13)
E/chromium(10085): #9      Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:835:14)
E/chromium(10085): #10     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:912:16)
E/chromium(10085): #11     Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:858:5)
E/chromium(10085): #12     _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:991:19)
E/chromium(10085): #13     Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:871:7)
E/chromium(10085): #14     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1466:15)
E/chromium(10085): #15     Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
```

**Comment by HansMuller** [comment]
That's just the first exception.  The rest of them are:

```
E/chromium(10085): [ERROR:dart_error.cc(16)] Unhandled exception:
E/chromium(10085): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 1359 pos 12: 'renderObject.child == child.renderObject' is not true.
E/chromium(10085): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium(10085): #1      OneChildRenderObjectWrapper.detachChildRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1359:12)
E/chromium(10085): #2      RenderObjectWrapper.detachRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1294:15)
E/chromium(10085): #3      Component.detachRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:773:14)
E/chromium(10085): #4      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:443:20)
E/chromium(10085): #5      OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1343:14)
E/chromium(10085): #6      Opacity.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:53:27)
E/chromium(10085): #7      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1095:5)
E/chromium(10085): #8      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:465:13)
E/chromium(10085): #9      Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:835:14)
E/chromium(10085): #10     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:912:16)
E/chromium(10085): #11     Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:858:5)
E/chromium(10085): #12     _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:991:19)
E/chromium(10085): #13     Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:871:7)
E/chromium(10085): #14     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1466:15)
E/chromium(10085): #15     Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
```

**Comment by abarth** [comment]
This seems related to the bug I'm working on for collin.  Something is getting screwed up in the syncing process...

**Comment by HansMuller** [comment]
Fixed in https://github.com/domokit/sky_engine/pull/1134
