### ISSUE TITLE
Skyx tool crashes while bundling material design icons

### ISSUE THREAD

**Issue by turu** [domokit/sky_engine#1077]
**Steps to reproduce:**
**1.** Add a following entry to your manifest:
```Yaml
material-design-icons:
  - name: image/lens
```
**2.** Run skyx tool

**Expected result:**
**1.** All 24dp variations of the ```image/lens``` icon (https://www.google.com/design/icons/#ic_lens) are present in the resulting archive.

**Actual result:**
**1.** Skyx tool crashes with the following stacktrace:
```Dart
Unhandled exception:
Uncaught Error: FileSystemException: Cannot open file, path = '/xxx/src/out/android_Debug/gen/dart-pkg/packages/material_design_icons/icons/image/drawable-xxhdpi/ic_lens_white_24dp.png' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _RootZone.runUnary (dart:async/zone.dart:1165)
#2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#3      _Future._propagateToListeners (dart:async/future_impl.dart:585)
#4      _Future._completeWithValue (dart:async/future_impl.dart:376)
#5      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#7      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:894)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

The root cause is that the Skyx tool assumes (https://github.com/domokit/sky_engine/blob/f0bdd4c590b0eed119eb86e506529d6fe18c9f6c/sky/tools/skyx/bin/skyx.dart#L58) that each material design icon declared in the manifest, has all possible combinations of ```density```, ```theme``` and ```size``` present in the icon set. 
This assumption is incorrect:
```Bash
$ cd path/to/material_design_icons
$ ls icons/image/drawable-xxhdpi/ | grep ic_lens
ic_lens_black_18dp.png
ic_lens_black_24dp.png
ic_lens_black_36dp.png
ic_lens_black_48dp.png
```
As you can see, the ```image/lens``` icon has no ```white```-themed version.

**Comment by abarth** [comment]
Thanks for the report.
