### ISSUE TITLE
Assertion errors when using a FloatingActionButton

### ISSUE THREAD

**Issue by mishadynin** [domokit/sky_engine#1166]
Pressing the floating button generates exceptions (see below), while switching to RaisedButton silences them.  Merged with a master branch of sky_engine.  Contact me if you need code to reproduce this.

```
E/chromium(30894): [ERROR:dart_error.cc(16)] Unhandled exception:
E/chromium(30894): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 874 pos 12: 'isFromOldGeneration' is not true.
E/chromium(30894): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium(30894): #1      Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:874:12)
E/chromium(30894): #2      _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:1010:19)
E/chromium(30894): #3      Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:889:7)
E/chromium(30894): #4      WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1487:15)
E/chromium(30894): #5      Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
E/chromium(30894): [ERROR:dart_error.cc(16)] Unhandled exception:
E/chromium(30894): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 874 pos 12: 'isFromOldGeneration' is not true.
E/chromium(30894): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium(30894): #1      Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:874:12)
E/chromium(30894): #2      _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:1010:19)
E/chromium(30894): #3      Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:889:7)
E/chromium(30894): #4      WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1487:15)
E/chromium(30894): #5      Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
E/chromium(30894): [ERROR:dart_error.cc(16)] Unhandled exception:
E/chromium(30894): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 874 pos 12: 'isFromOldGeneration' is not true.
E/chromium(30894): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium(30894): #1      Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:874:12)
E/chromium(30894): #2      _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:1010:19)
E/chromium(30894): #3      Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:889:7)
E/chromium(30894): #4      WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1487:15)
E/chromium(30894): #5      Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
E/chromium(30894): [ERROR:dart_error.cc(16)] Unhandled exception:
E/chromium(30894): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 874 pos 12: 'isFromOldGeneration' is not true.
E/chromium(30894): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium(30894): #1      Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:874:12)
E/chromium(30894): #2      _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:1010:19)
E/chromium(30894): #3      Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:889:7)
E/chromium(30894): #4      WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1487:15)
E/chromium(30894): #5      Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
```

**Comment by Hixie** [comment]
Yeah I saw this on the stocks demo earlier. Tapping the fab throws an exception. Even with my in-progress fix for popup menus (which removes a lot of the "generation" tests), it blinks red.

**Comment by Hixie** [comment]
I think I've fixed this (though maybe by #1180 and #1175, which aren't yet checked in).

**Comment by mishadynin** [comment]
I'll test it tomorrow and see if it works.

**Comment by mishadynin** [comment]
Looks like this is fixed on the master branch.
