### ISSUE TITLE
Exception syncing Mimicable - null child

### ISSUE THREAD

**Issue by apwilson** [domokit/sky_engine#1211]
```
I/sky     (21083): Exception caught while syncing children of Mimicable([GlobalKey Object(153376314)]; hashCode=81685225; mounted; gen-14; dirty; stateful})
I/sky     (21083): null
I/sky     (21083): The null object does not have a setter 'child='.
I/sky     (21083): 
I/sky     (21083): NoSuchMethodError: method not found: 'child='
I/sky     (21083): Receiver: null
I/sky     (21083): Arguments: [null]
I/sky     (21083): Stack trace:
I/sky     (21083): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
I/sky     (21083): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
I/sky     (21083): #2      OneChildRenderObjectWrapper.detachChildRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1392:18)
I/sky     (21083): #3      RenderObjectWrapper.detachRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1326:15)
I/sky     (21083): #4      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:474:22)
I/sky     (21083): #5      Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:811:16)
I/sky     (21083): #6      StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:911:16)
I/sky     (21083): #7      Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:848:5)
I/sky     (21083): #8      _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:993:19)
I/sky     (21083): #9      Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:861:7)
I/sky     (21083): #10     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1498:15)
I/sky     (21083): #11     Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
```

**Comment by apwilson** [comment]
Oops I wasn't in checked mode so likely a different issue.
