### ISSUE TITLE
Should be possible to put a NetworkImage in a VariableHeightScrollable

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/sky_engine#169]
I'm trying to do something like this:
```dart
Widget _builder(int index) {
    var src = "http://example.com/foo.gif";
    return new NetworkImage(src: src, size: const Size(48.0, 48.0));
}

new VariableHeightScrollable(
    builder: _builder,
    token: model.itemCount)
```

which gives a stack like this:
```
The null object does not have a method 'constrain'.

NoSuchMethodError: method not found: 'constrain'
Receiver: null
Arguments: [Instance of 'Size']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      RenderImage._sizeForConstraints (http://127.0.0.1:9998/packages/sky/rendering/box.dart:1304:26)
#3      RenderImage.getMaxIntrinsicHeight (http://127.0.0.1:9998/packages/sky/rendering/box.dart:1356:12)
#4      RenderProxyBox.getMaxIntrinsicHeight (http://127.0.0.1:9998/packages/sky/rendering/box.dart:507:20)
#5      RenderConstrainedBox.getMaxIntrinsicHeight (http://127.0.0.1:9998/packages/sky/rendering/box.dart:578:20)
#6      BlockViewport._getWidget (http://127.0.0.1:9998/packages/sky/widgets/block_viewport.dart:176:71)
#7      BlockViewport.layout (http://127.0.0.1:9998/packages/sky/widgets/block_viewport.dart:204:25)
#8      RenderObject.invokeLayoutCallback (http://127.0.0.1:9998/packages/sky/rendering/object.dart:277:13)
#9      RenderBlockViewport.performLayout (http://127.0.0.1:9998/packages/sky/rendering/block.dart:197:9)
#10     RenderObject.layout (http://127.0.0.1:9998/packages/sky/rendering/object.dart:242:5)
#11     RenderProxyBox.performLayout (http://127.0.0.1:9998/packages/sky/rendering/box.dart:519:13)
#12     RenderSizeObserver.performLayout (http://127.0.0.1:9998/packages/sky/rendering/box.dart:1504:24)
#13     RenderObject.layout (http://127.0.0.1:9998/packages/sky/rendering/object.dart:242:5)
#14     RenderProxyBox.performLayout (http://127.0.0.1:9998/packages/sky/rendering/box.dart:519:13)
#15     RenderObject.layout (http://127.0.0.1:9998/packages/sky/rendering/object.dart:242:5)
#16     RenderScaffold.performLayout (http://127.0.0.1:9998/packages/sky/widgets/scaffold.dart:116:12)
#17     RenderObject.layout (http://127.0.0.1:9998/packages/sky/rendering/object.dart:242:5)
#18     RenderView.performLayout (http://127.0.0.1:9998/packages/sky/rendering/box.dart:1601:13)
#19     RenderObject.layoutWithoutResize (http://127.0.0.1:9998/packages/sky/rendering/object.dart:194:7)
#20     RenderObject.flushLayout.<anonymous closure> (http://127.0.0.1:9998/packages/sky/rendering/object.dart:173:16)
#21     List.forEach (dart:core-patch/growable_array.dart:234)
#22     RenderObject.flushLayout (http://127.0.0.1:9998/packages/sky/rendering/object.dart:171:54)
#23     SkyBinding._beginFrame (http://127.0.0.1:9998/packages/sky/rendering/sky_binding.dart:73:18)
#24     _beginFrame (http://127.0.0.1:9998/packages/sky/base/scheduler.dart:30:13)
```

I can work around it with this patch:
```
--- a/third_party/sky_sdk/sky/lib/widgets/basic.dart
+++ b/third_party/sky_sdk/sky/lib/widgets/basic.dart
@@ -538,7 +538,11 @@ class FutureImage extends StatefulComponent {
   }
 
   Widget build() {
-    return new Image(image: _resolvedImage, size: size, colorFilter: colorFilter);
+    if (_resolvedImage == null) {
+      return new Text("loading...");
+    } else {
+      return new Image(image: _resolvedImage, size: size, colorFilter: colorFilter);
+    }
   }
 }
```

But I have no idea what the correct fix is here.

/cc @abarth @HansMuller

**Comment by abarth** [comment]
Does this PR fix the issue:
https://github.com/domokit/sky_engine/pull/170

I just wrote that in the web editor.  I can try it tomorrow in the office.
