### ISSUE TITLE
Fitness App dies with Unhandled exception: Class 'PaintingCanvas' has no instance method 'drawColor'.

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#537]
I suspect this is a sky package version mismatch?

I'm at 3deac04f05252d73974c46a6530c7d8b982638c3

I'm running:
```
./sky/tools/gn --android --release
ninja -C out/android_Release
cd examples/fitness
pub get
./packages/sky/sky_tool start --build-path ../../out/android_Release
```

This exact setup was working a couple hours ago.

@abarth @iansf 

Presumably we could detect this kind of thing and show a message earlier?  That the version of the sky engine i'm telling sky_tool to use was not design to work with this version of package: sky or something?

```
E/chromium(11636): [ERROR:dart_error.cc(19)] Unhandled exception:
E/chromium(11636): Class 'PaintingCanvas' has no instance method 'drawColor'.
E/chromium(11636): 
E/chromium(11636): NoSuchMethodError: method not found: 'drawColor'
E/chromium(11636): Receiver: Instance of 'PaintingCanvas'
E/chromium(11636): Arguments: [Instance of 'Color', Instance of 'TransferMode']
E/chromium(11636): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
E/chromium(11636): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
E/chromium(11636): #2      RenderView.paintFrame (http://localhost:9888/packages/sky/rendering/box.dart:1723:14)
E/chromium(11636): #3      SkyBinding.beginFrame (http://localhost:9888/packages/sky/rendering/sky_binding.dart:75:17)
E/chromium(11636): #4      WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/widgets/framework.dart:1223:21)
E/chromium(11636): #5      _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:30:13)
E/chromium(11636): [ERROR:dart_error.cc(28)] #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
E/chromium(11636): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
E/chromium(11636): #2      RenderView.paintFrame (http://localhost:9888/packages/sky/rendering/box.dart:1723:14)
E/chromium(11636): #3      SkyBinding.beginFrame (http://localhost:9888/packages/sky/rendering/sky_binding.dart:75:17)
E/chromium(11636): #4      WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/widgets/framework.dart:1223:21)
E/chromium(11636): #5      _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:30:13)
```

**Comment by eseidelGoogle** [comment]
This looks to be more general than the fitness app.  I have a freshly created demo app using `sky_tools init` and I'm hitting this.

```
% pub deps

charted_sky 0.0.0
'-- sky 0.0.29
    |-- cassowary 0.1.7
    |-- material_design_icons 0.0.2
    |-- mojo 0.0.22
    |-- mojo_services 0.0.22
    |   '-- mojo...
    |-- newton 0.1.2
    |-- sky_engine 0.0.7
    |-- sky_services 0.0.7
    |   '-- mojo...
    |-- sky_tools 0.0.8+1
    |   |-- args 0.13.2
    |   |-- mustache4dart 1.0.10
    |   |-- path 1.3.6
    |   |-- shelf 0.6.2
    |   |   |-- path...
    |   |   |-- collection 1.1.1
    |   |   |-- http_parser 0.0.2+8
    |   |   |   |-- collection...
    |   |   |   |-- crypto 0.9.0
    |   |   |   '-- string_scanner 0.1.3+1
    |   |   |       |-- path...
    |   |   |       '-- source_span 1.1.2
    |   |   |           '-- path...
    |   |   '-- stack_trace 1.3.4
    |   |       '-- path...
    |   |-- shelf_route 0.13.4
    |   |   |-- path...
    |   |   |-- shelf...
    |   |   |-- matcher 0.12.0+1
    |   |   |-- option 1.1.0
    |   |   |   |-- concepts 0.2.0
    |   |   |   '-- either 0.1.8
    |   |   |       '-- option...
    |   |   |-- shelf_path 0.1.6
    |   |   |   '-- shelf...
    |   |   '-- uri 0.10.0
    |   |       |-- matcher...
    |   |       |-- quiver 0.20.0
    |   |       |   '-- path...
    |   |       '-- utf 0.9.0+2
    |   '-- shelf_static 0.2.3
    |       |-- http_parser...
    |       |-- path...
    |       |-- shelf...
    |       '-- mime 0.9.3
    '-- vector_math 1.4.3
```

**Comment by eseidelGoogle** [comment]
I tried downgrading to sky 0.0.28 and 0.0.27, neither appeared to fix the problem.  Even when using 1sky_tool start --install`

**Comment by eseidelGoogle** [comment]
This feels like sky_engine is out of date and needs to be republished.

**Comment by eseidelGoogle** [comment]
This turned out to be that I had another sky_server running on the same port. :(

sky_tool really needs to fail hard in that case.
