### ISSUE TITLE
Fitness app crashes if you hit "enter" while entering a weight

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#543]
1. Hit the "+"
2. Select "measure", hit "Add"
3. Type a number "24"
4. Hit the enter key on the keyboard (return arrow)
5.  Hit "save" in upper right corner of the screen (being surprised that the enter key didn't do that for you).

Boom!

```
E/chromium(18489): [ERROR:dart_error.cc(19)] Unhandled exception:
E/chromium(18489): The null object does not have a getter 'iterator'.
E/chromium(18489): 
E/chromium(18489): NoSuchMethodError: method not found: 'iterator'
E/chromium(18489): Receiver: null
E/chromium(18489): Arguments: []
E/chromium(18489): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
E/chromium(18489): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
E/chromium(18489): #2      List.addAll (dart:core-patch/growable_array.dart:182)
E/chromium(18489): #3      SnackBar.build (http://localhost:9888/packages/sky/widgets/snack_bar.dart:75:8)
E/chromium(18489): #4      Component._sync (http://localhost:9888/packages/sky/widgets/framework.dart:648:14)
E/chromium(18489): #5      Widget.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:337:13)
E/chromium(18489): #6      Scaffold.syncRenderObject (http://localhost:9888/packages/sky/widgets/scaffold.dart:226:22)
E/chromium(18489): #7      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/widgets/framework.dart:889:5)
E/chromium(18489): #8      Widget.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:337:13)
E/chromium(18489): #9      StatefulComponent.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:746:27)
E/chromium(18489): #10     Component._sync (http://localhost:9888/packages/sky/widgets/framework.dart:651:14)
E/chromium(18489): #11     StatefulComponent._sync (http://localhost:9888/packages/sky/widgets/framework.dart:730:16)
E/chromium(18489): #12     Component._buildIfDirty (http://localhost:9888/packages/sky/widgets/framework.dart:666:5)
E/chromium(18489): #13     StatefulComponent._buildIfDirty (http://localhost:9888/packages/sky/widgets/framework.dart:700:24)
E/chromium(18489): #14     _buildDirtyComponents (http://localhost:9888/packages/sky/widgets/framework.dart:805:19)
E/chromium(18489): #15     Component.flushBuild (http://localhost:9888/packages/sky/widgets/framework.dart:679:7)
E/chromium(18489): #16     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/widgets/framework.dart:1222:15)
E/chromium(18489): #17     _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:30:13)
E/chromium(18489): [ERROR:dart_error.cc(28)] #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
```

**Comment by eseidelGoogle** [comment]
This is fixed, but the "enter" key still doesn't work.  I'll file a new bug for that.
